include:
  - path: ./docker-compose-base.yml
    env_file: ./.env

services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
      es01:
        condition: service_healthy
    # image: infiniflow/ragflow:${RAGFLOW_VERSION}
    build:
      context: ../
      dockerfile: Dockerfile
      # target: web
    container_name: ragflow-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 9080:9080
      - 9443:9443
    volumes:
      - ./service_conf.yaml:/ragflow/conf/service_conf.yaml
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

      - ../api/apps/llm_app.py:/ragflow/api/apps/llm_app.py
      - ../api/apps/conversation_app.py:/ragflow/api/apps/conversation_app.py
      - ../agent/settings.py:/ragflow/agent/settings.py
      - ../api/apps/conversation_app.py:/ragflow/api/apps/conversation_app.py
      - ../api/settings.py:/ragflow/api/settings.py
      - ../api/db/db_models.py:/ragflow/api/db/db_models.py
      - ../api/settings.py:/ragflow/api/settings.py
      - ../rag/settings.py:/ragflow/rag/settings.py
      - ../agent/settings.py:/ragflow/agent/settings.py


      # - ../api:/ragflow/api
      # - ../conf:/ragflow/conf
      # - ../deepdoc:/ragflow/deepdoc
      # - ../rag:/ragflow/rag
      # - ../agent:/ragflow/agent
      # - ../graphrag:/ragflow/graphrag
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=https://huggingface.co
      - MACOS=${MACOS}
    networks:
      - ragflow
    restart: always
